### ISSUE TITLE
Crash with spawn_item Command and Specific Items

### ISSUE THREAD

**Issue by john7200** [grimdoomer/DeadRisingEx#7]
I am not sure if this is an issue with DeadRisingEx, the game or both.

Two item ID, specifically 69 (Queen) and 135 (Sniper Rifle) always crash the game. If spawn_item 69 or spawn_item 135 is entered in the console, the game will freeze for about 2-3 seconds before crash to desktop. It is always reproducible.

Possible corruption with game file(s) can be ruled out because I have verified all files or data with Steam and Steam client didn't download anything.

I have tried with other items or objects, including animating items like molotov (which has flame on its fuse) and the game never crashed, even after a lot of items were spawned.

The Queen will not be spawned in game until a certain time, period or event at the warehouse is occurred in the evening. At first I thought the game crashed because I needed to wait until that certain event occur first before spawning the particular item. But even long after that event occurred, the game would always crash whenever I used spawn_item 69.

The same thing goes with item 135. There's no restriction (event wise) with the sniper rifle because even though certain bosses (psychopaths) use the firearm only during a certain event, the firearm is available since the beginning of the game and can be obtained from the Gun Store at North Plaza immediately.

Both items are not quest, case or mission related. Perhaps there is an exception for Queen considering the event at the warehouse in the evening, but I am not sure if it is event related because like I mentioned, the game will crash everytime the command spawn_item 69 is entered regardless of in-game progress.

I am wondering if this is an issue with using DeadRisingEx to spawn certain items or objects.

**Comment by grimdoomer** [comment]
Fixed in commit https://github.com/grimdoomer/DeadRisingEx/commit/84825253ca894dd864152cfba4e21e158e84585f, you can get the fix via auto update or download the new release [v1.5.10.58.](https://github.com/grimdoomer/DeadRisingEx/releases/tag/v1.5.10.58)

Dev notes: Sniper rifle and queen bee both have two DTI implementations, one for a "static" object and one for an "item" object. The spawn item code used the static object DTI (by virtue of the how it derives the DTI type name from the arc file path) which did not set the itemId property for the uItem base class, and when checking item properties would null deref trying to load item properties for item 0. I added a switch block to append "_1" to the DTI type name for these items which references the "item" object and correctly sets the itemId property in the ctor.

**Comment by john7200** [comment]
I appreciate the update a lot, but I appreciate the technical details even more.
Thank you very much for taking time to solve and explain everything in details.
